### ISSUE TITLE
Add type

### ISSUE THREAD

**Issue by enieber** [ogilvieira/dev-podcast-list-brazil#16]
seria legal ter a informação de que tipo é o podcast.
exemplo: Javascript, Front-end, Android, Angular, etc...

**Comment by ogilvieira** [comment]
Legal! mas ai teriamos que criar um sistema para receber os links, usando markdown a galera pode dar ctrl+c + ctrl+v e ir adicionando novidades, por isso escolhemos deste modo

**Comment by ogilvieira** [comment]
Sim! se puder, faça um fork e depois mande um PR com sua proposta com as informações

**Comment by enieber** [comment]
O que você acha em definirmos alguns tipos básicos?

**Comment by ogilvieira** [comment]
Então, alguns são de ciência (mas têm episódios de programação) e outros são talk shows em inglês que ~ás vezes~ tem algum episódio sobre programação... acho dificíl definir já que todos tem semelhanças somente alguns fojem de uma descrição comum. O Castálio podcast é mais voltado a entrevistas, o DevNaEstrada é mais com front-end e outros como Hack'n'cast é sobre programação e abordou até sistemas embarcados... dificíl estabeler descrições curtas já que a própria bio do podcast no site ou no itunes revela o objetivo do podcast e como ele quer se comunicar, mas faz um Fork + PR que quem sabe podemos adotar sua alteração
