### ISSUE TITLE
melhora na manutenção

### ISSUE THREAD

**Issue by enieber** [ogilvieira/dev-podcast-list-brazil#17]
Uma ideia para melhorar a manutenção do codio seria criar um site onde daria pra adicionar ou alterar algum link, alem de poder ser colocado icones em cada podecast para ficar mais intuitivo.

**Comment by ogilvieira** [comment]
Legal! mas ai teriamos que criar um sistema para receber os links, usando markdown a galera pode dar ctrl+c + ctrl+v e ir adicionando novidades, por isso escolhemos deste modo
