### ISSUE TITLE
O Podcast precisa estar no Itunes?

### ISSUE THREAD

**Issue by camilatigre** [ogilvieira/dev-podcast-list-brazil#63]
Vi que todos os links mandam pro itunes mas eu uso linux e é a maior complicação pra usar ele. Posso linkar pro site do podcast?

**Comment by enieber** [comment]
existe links para o site dos podcasts, não necessariamente precisa estar no Itunes, exemplo disso é o do [sciecast](http://deviante.com.br/), só clicar no nome do podcast...

**Comment by camilatigre** [comment]
ah. nosso viajei, tem o link do lado esquedo. eu já tinha visto até. obrigada, logo logo abro um pr ((:
